#!/bin/bash
#
# template generated by genshtest
# This is bisect for nightly unittest-ubsan, integer
#
#


build_dir=~/bisectav1/build

cd $build_dir

#read testcase  

cd $build_dir
rm -r -f *


cmake ../aom/ -DENABLE_CCACHE=1 -DENABLE_DOCS=0 -DCONFIG_UNIT_TESTS=1 -DCMAKE_C_FLAGS_RELEASE=-O3 -DCMAKE_CXX_FLAGS_RELEASE=-O3 -DAOM_TARGET_CPU=generic && make -j12 && make testdata

ASAN_OPTIONS=
ASAN_OPTIONS=:handle_segv=0
ASAN_OPTIONS=:handle_segv=0:abort_on_error=1
ASAN_OPTIONS=:handle_segv=0:abort_on_error=1:fast_unwind_on_fatal=1
ASAN_OPTIONS=:handle_segv=0:abort_on_error=1:fast_unwind_on_fatal=1:detect_stack_use_after_return=1
ASAN_OPTIONS=:handle_segv=0:abort_on_error=1:fast_unwind_on_fatal=1:detect_stack_use_after_return=1:max_uar_stack_size_log=17
ASAN_OPTIONS=:handle_segv=0:abort_on_error=1:fast_unwind_on_fatal=1:detect_stack_use_after_return=1:max_uar_stack_size_log=17:log_path=asan_log
export ASAN_OPTIONS


cd ~/bisect

cat testcase.txt > ~/bisectav1/build/case

cd ~/bisectav1/build
tc=$(cat "case")

sh ../aom/test/examples.sh --bin-path examples --verbose --show-program-output --run-disabled-tests --filter $tc
