#!/bin/bash
#
# template generated by genshtest
# This is bisect for nightly unittest-ubsan, integer
#
#


build_dir=~/bisectav1/build

cd $build_dir

#read testcase  


cd $build_dir
rm -r -f *

arch=x86-linux-gcc
find /opt/clang-5.0.1/lib -name libclang_rt.builtins-i386.a -print -quit
clang_rt=/opt/clang-5.0.1/lib/clang/5.0.1/lib/linux/libclang_rt.builtins-i386.a
echo extralibs += /opt/clang-5.0.1/lib/clang/5.0.1/lib/linux/libclang_rt.builtins-i386.a
toolchain_file=~/bisectav1/aom/build/cmake/toolchains/x86-linux.cmake

cmake ~/bisectav1/aom -DSANITIZE=undefined -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS=-O1 -DCMAKE_CXX_FLAGS=-O1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-Wl,--start-group /opt/clang-5.0.1/lib/clang/5.0.1/lib/linux/libclang_rt.builtins-i386.a" -DCMAKE_TOOLCHAIN_FILE=~/bisectav1/aom/build/cmake/toolchains/x86-linux.cmake -DENABLE_CCACHE=1


make -j12 && make testdata

cd ~/bisect

cat testcase.txt > ~/bisectav1/build/case

cd ~/bisectav1/build
tc=$(cat "case")

./test_libaom --gtest_filter=$tc
   
