#!/bin/bash
# template generated by genshtest
# This is bisect for nightly unittest-ubsan, integer
#
#


build_dir=~/bisectav1/build

cd $build_dir

#read testcase  

cd $build_dir
rm -r -f *

cmake ../aom/ -DENABLE_CCACHE=1 -DENABLE_DOCS=0 -DCONFIG_UNIT_TESTS=1 -DCMAKE_C_FLAGS_RELEASE=-O3 -DCMAKE_CXX_FLAGS_RELEASE=-O3 -DCONFIG_LOWBITDEPTH=1 && make -j12 && make testdata

cd ~/bisect

cat testcase.txt > ~/bisectav1/build/case

cd ~/bisectav1/build
tc=$(cat "case")

valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./test_libaom --gtest_filter=$tc
   
